DROP DATABASE IF EXISTS DBEMAILS;

CREATE DATABASE DBEMAILS;
USE DBEMAILS;

CREATE TABLE EMAILS (
    EMAIL   VARCHAR(255)    NOT NULL,
    DATEAT  DATETIME        NOT NULL,
    PRIMARY KEY (`EMAIL`)
);